version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: ubuntu
      WORDPRESS_DB_PASSWORD: ubuntuasdf
      WORDPRESS_DB_NAME: wordpress_test_db
    volumes:
      - ./wordpress_volumes/wordpress:/var/www/html

  wordpress_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_test_db
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: ubuntuasdf
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./wordpress_volumes/db:/var/lib/mysql

volumes:
  wordpress:
  wordpress_db:

